spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

    username: ${JDBC_DATABASE_USERNAME:misha}
    password: ${JDBC_DATABASE_PASSWORD:password}
    initialization-mode: never
  jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
